name: Build crankshaft

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-13, ubuntu-latest, windows-latest]

    steps:
      - name: Install g++-multilib
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install g++-multilib

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build and release if the draft exists
        run: pnpm run dist
        env:
          GH_TOKEN: ${{ secrets.github_token }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.os }}
          path: dist/crankshaft-*
  release:
    needs: build

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Create nightly release
        uses: softprops/action-gh-release@v2
        with:
          files: binaries-*/*
          body_path: ${{ github.workspace }}/.github/workflows/notes.md
          name: Nightly release
          tag_name: nightly
          prerelease: true
